import ProductsPage from "./ProductsPage";

const Deluxe = () => {
  const para1 =
    "Praesent justo erat, vestibulum et mi in, euismod sodales augue. Maecenas scelerisque eu metus eu consectetur. Vivamus et pulvinar diam. Suspendisse tempor pellentesque sodales. Donec non dolor orci. Quisque iaculis tempor accumsan. Vestibulum urna leo, faucibus a felis eu, pellentesque iaculis ex. Donec sit amet felis facilisis risus tempus mattis. Nunc sodales hendrerit accumsan. Nullam non malesuada ex. Suspendisse potenti. Praesent diam dolor, condimentum sit amet mi a, scelerisque varius metus. Fusce eu egestas eros. Donec et malesuada lacus, eu porttitor diam. Nam pharetra sed eros vitae cursus. Aliquam ante dolor, congue sit amet mauris id, hendrerit pulvinar eros. In hac habitasse platea dictumst. Duis sit amet magna tempus, sollicitudin nisl vel, mattis neque. Cras placerat est quis nunc elementum tempus. Suspendisse suscipit aliquet ultricies. Morbi vulputate ligula vitae posuere luctus. Donec nec porta augue. Fusce ornare, massa in porta volutpat, metus est lobortis mauris, sed tincidunt ligula libero nec odio. Mauris lobortis volutpat elit, in facilisis turpis commodo ac.Aliquam eu enim turpis. Cras vel varius ante. Mauris hendrerit placerat arcu, tristique finibus lorem. Duis efficitur congue mauris vitae elementum. Quisque viverra faucibus odio. Aenean gravida lectus purus, quis interdum mauris pulvinar vel. Morbi pulvinar suscipit nulla, et rhoncus ex lobortis eget. Aliquam et congue tortor. Praesent vitae justo.";
  const para2 =
    "Duis ac finibus ex. Curabitur vitae lacus vitae lorem consequat tincidunt ut vel massa. In pretium dui a tellus maximus, quis pellentesque sem ullamcorper. Ut lacus dolor, varius gravida tempus eu, consequat eget diam. Donec viverra convallis porta. Suspendisse ut magna vulputate, dignissim arcu vitae, pulvinar felis. Donec efficitur condimentum urna, sed tempor massa dapibus vitae. Quisque id velit a neque venenatis viverra. Nunc venenatis risus erat. Proin malesuada, nisl non aliquet efficitur, ex purus luctus magna, sed scelerisque mauris metus vel lacus. Fusce in auctor lorem. Proin ut dapibus ipsum. Curabitur mollis sapien efficitur interdum aliquam. Donec lobortis odio quis congue pulvinar. Nam vel neque sapien. Vestibulum hendrerit venenatis leo, vitae lobortis mauris viverra nec. Praesent gravida, justo quis aliquet porta, neque mi congue enim, in volutpat arcu velit eu nisi. Nulla facilisi. Proin maximus ornare elit ac cursus. Suspendisse id turpis eget velit pretium tincidunt. Sed ac ex elit. Nam lacus ligula, vestibulum in congue vel, elementum sit amet nisl. Pellentesque eu augue et ante fringilla malesuada. Curabitur sem augue, dapibus id quam quis, pharetra aliquet magna. Aenean pretium metus non eros fermentum consectetur. Morbi ac condimentum arcu. In rutrum metus pellentesque ex venenatis tempor. Maecenas eget pulvinar augue, non vulputate purus. Duis tempus imperdiet sapien, at condimentum.";

  return <ProductsPage title="Deluxe" para1={para1} para2={para2} />;
};

export default Deluxe;
