import ProductsPage from "./ProductsPage";

const Luxury = () => {
  const para1 =
    "Etiam diam mi, pulvinar nec dapibus eu, consequat eu justo. Morbi in orci eu ipsum gravida aliquet ut at nisi. Integer non libero augue. Nulla tristique enim ac nisl sagittis tristique. Maecenas turpis purus, ullamcorper sit amet hendrerit et, tempus et urna. Praesent sed dolor nec leo rutrum feugiat. In ac rhoncus ante, et pretium turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc vitae nulla eget justo fermentum scelerisque a id felis. Maecenas ac ultrices orci, at hendrerit justo. Sed elementum lorem sit amet tristique malesuada. Vestibulum finibus consectetur nisi, ac aliquet dui sagittis eget. Pellentesque ullamcorper feugiat faucibus. Nullam viverra, diam vel iaculis fringilla, sem ex scelerisque erat, eu lobortis ligula nisl vel risus. Nulla tempus velit ut nunc accumsan elementum. Nullam nisl metus, ultrices ut pretium non, dictum fermentum augue. Phasellus pulvinar lorem eu erat congue dictum. Phasellus in lectus eu neque commodo ultrices id eget neque. In hac habitasse platea dictumst. Nullam feugiat massa eu tortor ultrices, eu viverra nibh varius. Nunc faucibus ullamcorper lacus ut dapibus. Donec at sapien massa. Etiam magna libero, mollis eu erat et, sagittis cursus tortor. Ut convallis orci enim, in sagittis nulla rhoncus et. Etiam scelerisque, tortor eu lacinia aliquam, massa lacus faucibus erat.";
  const para2 =
    "Nulla in faucibus lorem, quis blandit sapien. Ut dapibus vehicula sem id placerat. Suspendisse commodo augue a magna hendrerit convallis. Cras eu interdum purus, eu dapibus lacus. Quisque iaculis gravida dui ut mollis. Sed mollis nisl ac gravida finibus. Donec scelerisque nibh enim, ut tincidunt ante euismod sed. In a velit sed lacus laoreet porttitor. Vivamus consectetur quam lacus, ac tristique tellus gravida non. Donec iaculis tincidunt risus vel congue. Vestibulum facilisis in ipsum in feugiat. Aliquam nulla risus, vehicula et lobortis sit amet, rutrum dictum enim. Vestibulum lacinia bibendum elit ut consequat. Quisque at neque vitae orci commodo rhoncus. Cras massa lectus, lacinia non orci nec, auctor eleifend ante.Donec vitae risus ex. Sed a libero quis lorem laoreet facilisis. Nunc tincidunt libero at mollis eleifend. Sed aliquet velit a massa auctor lacinia. Proin tincidunt nulla nisl, vulputate euismod arcu dictum id. Sed in risus eget urna commodo aliquam. Curabitur a felis massa. Aenean porttitor mauris sit amet odio imperdiet, et congue nisi placerat. Fusce id hendrerit ex. Donec gravida tellus sem, quis varius metus consectetur pulvinar. Vivamus diam diam, rhoncus et porttitor et, posuere vitae metus. Etiam accumsan ante mollis elit tempor maximus. In maximus faucibus odio, sit amet volutpat massa mattis sit amet. Integer bibendum quam in.";

  return <ProductsPage title="Luxury" para1={para1} para2={para2} />;
};

export default Luxury;
