import ProductsPage from "./ProductsPage";

const Superior = () => {
  const para1 =
    "Morbi suscipit nec dolor eget imperdiet. Morbi vulputate felis non lacinia sagittis. Nulla auctor aliquet porttitor. Integer sit amet posuere purus. Vivamus quis erat ac tellus consectetur dictum ut facilisis nisi. Phasellus nulla ante, volutpat vitae sollicitudin quis, venenatis vitae massa. Aenean ac est vel tellus porta iaculis fermentum eu ligula. Etiam et bibendum enim. Sed ut dui in augue egestas malesuada eget ultricies est. Cras gravida, mi auctor varius porttitor, tellus nunc elementum libero, vel ornare quam quam et ex. Pellentesque nisl risus, feugiat varius tristique nec, elementum ac neque. Nunc aliquet eros non blandit imperdiet. Fusce efficitur nibh commodo tempus accumsan. Fusce nec porta ligula, nec mattis enim. Etiam dictum leo vitae nibh tristique rhoncus. Nunc at porttitor nisi, eget interdum leo. Nulla porttitor congue dolor, non viverra risus vestibulum molestie. Praesent sem sapien, fringilla ut luctus ac, ullamcorper nec tellus. Donec vitae purus turpis. Donec et pretium turpis, in auctor mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In eu porttitor risus, et aliquam enim. Nulla orci lacus, vehicula eu odio id, consequat finibus justo. Aenean porta nec elit ac accumsan. Mauris eget placerat orci. Cras in sem id risus commodo condimentum. Donec sit amet cursus neque. Nulla egestas, urna a tristique.";
  const para2 =
    "Vivamus malesuada ornare facilisis. Etiam gravida ex at purus feugiat commodo. Sed id odio sed risus congue pellentesque et eu nibh. Integer at posuere dolor. Sed interdum dignissim diam, eget sollicitudin ipsum mollis ut. Ut auctor nisl ac porta eleifend. Praesent mollis vitae est ac aliquet. Cras venenatis nec ante non rhoncus. Mauris dapibus lobortis lectus, id tincidunt sem ornare id. Morbi lobortis vestibulum tellus eu condimentum. Praesent at sem non magna consectetur varius ultrices ac ligula. Vivamus sit amet tristique dui, sit amet convallis nunc. Nam pretium lobortis mi ac tempus. Integer feugiat rutrum ante, id auctor tellus auctor non. Integer vitae nulla varius, porta tortor non, gravida est. Aenean a lorem augue. Pellentesque vitae elementum diam, id placerat magna. Fusce ut aliquam metus. Phasellus dapibus risus vel magna condimentum blandit. Sed eget sollicitudin dolor. Integer efficitur turpis in sodales auctor. Duis condimentum, elit vitae vulputate volutpat, enim arcu egestas lacus, non dignissim augue sem sit amet quam. Morbi non varius nibh. Nulla a aliquam quam. Pellentesque tristique mauris diam, non aliquam lacus ornare vitae. In aliquam lacinia semper. Maecenas id dolor ut sapien pulvinar scelerisque. Vestibulum egestas consequat justo ac lobortis. Donec interdum placerat feugiat. Duis justo lorem, malesuada ut sodales at, tristique feugiat eros. Vestibulum volutpat eget.";

  return <ProductsPage title="Superior" para1={para1} para2={para2} />;
};

export default Superior;
